ALTER TABLE IF EXISTS works
    DROP CONSTRAINT IF EXISTS work_contract_fk;
ALTER TABLE IF EXISTS works
    DROP CONSTRAINT IF EXISTS work_project_fk;
ALTER TABLE IF EXISTS works
    DROP COLUMN IF EXISTS contract_id;
ALTER TABLE IF EXISTS works
    DROP COLUMN IF EXISTS project_id;
