ALTER TABLE IF EXISTS contracts
    ADD COLUMN IF NOT EXISTS name VARCHAR(512) NULL;
ALTER TABLE IF EXISTS projects
    ADD COLUMN IF NOT EXISTS name VARCHAR(512) NULL;
ALTER TABLE IF EXISTS groups
    ADD COLUMN IF NOT EXISTS name VARCHAR(512) NULL;
ALTER TABLE IF EXISTS works
    ADD COLUMN IF NOT EXISTS name VARCHAR(512) NULL;
ALTER TABLE IF EXISTS equipment
    ADD COLUMN IF NOT EXISTS name VARCHAR(512) NULL;
